name: Download Maven Artifact

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub project
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Download Maven Artifact
        id: download-maven-artifact
        uses: clausnz/github-action-download-maven-artifact@1.0.0
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId: 'javax.mail'
          artifactId: 'mail'
          version: '1.5.0-b01'
          extension: 'jar'

      - name: Output file path in container
        run: |
          echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
